### ISSUE TITLE
Why does negotiation does not work for multiple types in the accept header?

### ISSUE THREAD

**Issue by frisi** [plone/plone.rest#100]
# Current state:

currently plone.rest returns a 404 for a request to the following service

```
  <plone:service
      method="GET"
      accept="application/json"
      for="Products.CMFPlone.interfaces.IPloneSiteRoot"
      factory=".rest.MyService"
      name="@servicename"
      permission="zope2.View"
      />
```

when the request is made with https://httpie.org/ like this

```
http --json GET https://server.com/@servicename
HTTP/1.1 404 Not Found
...
```

# Reason:

https://github.com/plone/plone.rest/blob/1.6.0/src/plone/rest/negotiation.py#L27
also documented in the docstring:
> Only Accept headers containing exactly one media type are considered for negotiation.

and httpie sends two media types in the accept header  `"Accept": "application/json, */*",`

```
http --debug --json GET https://server.com/@servicename
HTTPie 0.9.8
...
>>> requests.request(**{
    "allow_redirects": false,
    "auth": "None",
    "cert": "None",
    "data": "",
    "files": {},
    "headers": {
        "Accept": "application/json, */*",
        "Content-Type": "application/json",
        "User-Agent": "HTTPie/0.9.8"
    },
    "method": "get",
    "params": {},
    "proxies": {},
    "stream": true,
    "timeout": 30,
    "url": "https://server.com/@servicename",
    "verify": true
})
```

# Possible solution

use first media type mentioned in accept header (if multiple are given) 

[or even return the service if one of the accept types matches.]

**Comment by frisi** [comment]
@buchi as you seem to have written the docstring (https://github.com/plone/plone.rest/commit/d58708953ba362d39119be78aa454627c7bff243): may i ask you to elaborate why this decision has been made?
thank you!

**Comment by tiberiuichim** [comment]
frisi: see answer in https://github.com/plone/plone.rest/issues/62 where I've asked the same question.
