### ISSUE TITLE
Python2 builds all broken

### ISSUE THREAD

**Issue by petri** [plone/plone.rest#112]
All (Python 2.7.x) Travis builds are currently broken because we have unpinned httpie as a dependency in base.cfg for the releaser section. I don't know what httpie is specifically needed for here to begin with but I guess there must be a reason.

httpie == 1.0.3 is the last Python2 version.

Can we just pin it down? It used to be pinned to 0.9.4 earlier, for what it's worth. Or... I cannot recall if buildout supports conditional pins per Python version being used to run it?

**Comment by petri** [comment]
Hm looks like we could have http://www.buildout.org/en/latest/topics/variables-extending-and-substitutions.html#conditional-configuration-sections depending on Python version.

**Comment by lukasgraf** [comment]
I'm fairly confident that `httpie` could safely be pinned down to `1.0.3`, and was only used as a soft-dependency for development convenience / local testing here.

It's certainly not used by the actual codebase of `plone.rest`, and I couldn't find any reference to it from zest.releaser or towncrier hooks in `setup.py`, `setup.cfg`, or `pyproject.toml`, so I don't think it's even used for cutting a release either.

But please note that @tisto also has a WIP PR open at #111 with several updates. So probably best coordinate with him. I would hate to throw a wrench in the works at this time that would make work for him harder in terms of merge conflicts, version pinnings etc.

But from my point of view, downpinning should be safe, and I'd actually prefer that to conditional buildout magic, unless necessary.

**Comment by petri** [comment]
Thanks. Looks like he's done the same down-pinning, in versions.cfg. This issue can be closed when #111 is merged.

**Comment by jugmac00** [comment]
#111 was merged back in December 2020
