### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by tisto** [plone/plone.rest#12]
When the client sends the 'application/json' Accept header and an error occurs, the ZServer should respond with a JSON encoded error message. Moved here from https://github.com/plone/plone.restapi/issues/23.

**Comment by jone** [comment]
We could do that by register a named adapter (```((Exception, IAPIRequest), name='index.html')```), which returns a JSON.
See https://github.com/zopefoundation/Zope/blob/2.13/src/Zope2/App/startup.py#L219-L240

**Comment by tisto** [comment]
https://github.com/plone/plone.rest/pull/19
