### ISSUE TITLE
Wrong id on the Plone site using the new traversal

### ISSUE THREAD

**Issue by sneridagh** [plone/plone.rest#124]
Request:
http://localhost:8080/Plone/++api++

Response

```
[..]

  "@id": "http://localhost:8080/Plone/++api++", 

[..]
```

it should be:

```
[..]

  "@id": "http://localhost:8080/Plone", 

[..]
```

This messes up some things, of course. It seems it only happens in the Plone site. Any ideas why?

/cc @jensens @ericof @tisto

**Comment by sneridagh** [comment]
I think it's p.restapi fault:

https://github.com/plone/plone.restapi/blob/master/src/plone/restapi/serializer/site.py#L46

Didn't we change this from the DX serializer already because it caused problems in the past?

**Comment by sneridagh** [comment]
How we can make that the tests use the new traversal (too)?

**Comment by sneridagh** [comment]
I think it's enough, @tisto reminded me that we decided that `@id` should map to `absolute_url()` and this was probably a remnant of the initial implementation 6 years ago from before taking the decision.

So I created the PR to amend it, like we did with the other objects.

**Comment by jensens** [comment]
BTW: http://localhost:8080/Plone/++api++?b_start=1&b_size=2 works perfectly fine
