### ISSUE TITLE
Can we cut a release for PyPi?

### ISSUE THREAD

**Issue by flipmcf** [plone/plone.rest#136]
I was told to create this ticket.

**Comment by flipmcf** [comment]
@mauritsvanrees @jensens :)

**Comment by tisto** [comment]
@flipmcf why do you want a release and what do you want to be included? The current master branch has nothing that is worth releasing.

**Comment by davisagli** [comment]
@tisto I discussed it with @flipmcf. It was a misunderstanding because the alphas are not easily visible on PyPI unless you know where to look.

**Comment by jensens** [comment]
We anyway should go final with this. Or do you plan to add breaking features before Plone 6 final?

**Comment by tisto** [comment]
Here ya go: https://pypi.org/project/plone.rest/2.0.0/
