### ISSUE TITLE
Fall back to Content-Type header when there is no Accept header

### ISSUE THREAD

**Issue by mauritsvanrees** [plone/plone.rest#154]
I am working on an API for a Plone website, based on plone.rest/plone.restapi.  The customer has asked a few of their users to try it out.  Most of the ones who reported back, were confused about the request headers that they needed to send.  Especially it seemed confusing to them that a POST request requires both a `Content-Type` header (indicating the type of data it sends), and an `Accept` header (for what type of answer it is ready to accept).  Of course both are usually `application/json`.

Can't `plone.rest` fall back to checking the `Content-Type` header if there is no `Accept` header?

If this idea is reasonable, I could make the change.  Seems easy enough at first glance, just requiring a change in [one line in `events.py`](https://github.com/plone/plone.rest/blob/3.0.0/src/plone/rest/events.py#L34), plus of course tests.  The devil may be in the details...

**Comment by davisagli** [comment]
This sounds like a really bad idea to me. There is a clear separation in HTTP; `Content-Type` specifies the type of the request body, and `Accept` specifies what types will be accepted in the response. Assuming that the user wants a response in the same format they made their request doesn't make sense in general, and it would be confusing for Plone to use these headers in a way that doesn't match the HTTP spec.

To avoid the need to set the `Accept` header, you can access the API with the `/++api++` prefix, which defaults to assuming `application/json` is accepted.

**Comment by mauritsvanrees** [comment]
Ah, of course!  That is much better.  Thanks.

Can you tell I don't do much with Volto yet? ;-)
