### ISSUE TITLE
Rename default branch from master to main

### ISSUE THREAD

**Issue by tisto** [plone/plone.rest#157]
@mauritsvanrees as a preparation for the plone.rest 4 release I renamed the default branch from master to main. I guess I have to amend buildout.coredev to reflect this change, right?

**Comment by tisto** [comment]
Running 6.1: https://jenkins.plone.org/job/plone-6.1-python-3.11/259/console

6.0 has been fixed already: https://jenkins.plone.org/job/plone-6.0-python-3.11/1026/

**Comment by mauritsvanrees** [comment]
Yes, thanks.  Seems fine now.
