### ISSUE TITLE
Version 3.0.1 breaks python2 support

### ISSUE THREAD

**Issue by pbauer** [plone/plone.rest#162]
https://github.com/plone/plone.rest/commit/db0cb9adb7f483bffb3e1ab06d1270c7db0b04a8 uses f-strings but that version claims to still support py2.

**Comment by davisagli** [comment]
@pbauer We made a 3.x branch and prepared a fix -- https://github.com/plone/plone.rest/commit/d5dea80d8afb8d10c888c596e905b18d37838956

CI for Python 2.7 is currently not running on GHA. Would you like to check that it works before we make a release?

**Comment by pbauer** [comment]
@davisagli @mauritsvanrees I tested it and tests are fine in py2.

**Comment by davisagli** [comment]
@pbauer I released plone.rest 3.0.2 with the fix. Thanks for the report.
