### ISSUE TITLE
Support for REST API  custom endpoints?

### ISSUE THREAD

**Issue by zopyx** [plone/plone.rest#24]
Is there some way to use plone.rest for custom endpoint like

PUT http://.../Plone/my/connector/crex/upload

where 'crex/upload' is a REST method specific to IConnector (implemented by the document under /my/connector). Is this somehow doable with plone.rest?

**Comment by lukasgraf** [comment]
@zopyx we implemented support for named services in #18 (see tests / `demo.zcml` for a usage example). Does this cover your use case?

**Comment by tisto** [comment]
@lukasgraf maybe we should add this use case to the README.rst as well.

**Comment by lukasgraf** [comment]
@tisto :+1: - will do

**Comment by zopyx** [comment]
Exactly what I need.
