### ISSUE TITLE
Support for upload and download of binary data?

### ISSUE THREAD

**Issue by zopyx** [plone/plone.rest#25]
A quick test shows that I can return binary data using

```
self.request.response.setHeader('content-type', 'application/zip')
self.request.response.write(zip_data)
```

Perfect.

Uploading a binary file using a POST request does not seem to work in the same way.
Of course you can upload binary data base64 encoded as part of the JSON payload however
this does not scale for larger binary data. 

Thoughts?

**Comment by zopyx** [comment]
A minor improvement for the working download story would be to support the filestream_iterator API.
plone.rest tried to convert a returned  filestream_iterator to JSON. The code checking for the return value of a method call should check for the type of the return value and treat the result in this case as None (same behavior as returning None above).

**Comment by zopyx** [comment]
https://github.com/plone/plone.rest/pull/29

supports filestream_iterator 

as result of an API call.

**Comment by buchi** [comment]
We're not going to handle upload or download in plone.rest.
