### ISSUE TITLE
Conflicts with existing IBrowserPublisher adapters

### ISSUE THREAD

**Issue by buchi** [plone/plone.rest#26]
Currently the REST service directive registers an `IBrowserPublisher` adapter which adapts the context and the request. During traversal ZPublisher uses the most specific adapter to publish the object. We add a browser layer (IGET, IPOST, etc.) to the request to make our adapter as specific as possible. However there are other adapters that are more specific on the context and get chosen instead of our adapter.

One example is the `ImageTraverser` adapter in plone.app.imaging. This adapter is registered for `plone.app.imaging.interfaces.IBaseObject` and `zope.publisher.interfaces.IRequest`. Because `plone.app.imaging.interfaces.IBaseObject` is inheriting from `Products.Archetypes.interfaces.BaseObject` this makes it impossible to register a REST service for `Products.Archetypes.interfaces.IBaseObject` as the `ImageTraverser` adapter is more specific on the context.

This is a general problem and can happen with other `IBrowserPublisher` adapters.

In my opinion we should make sure that a REST service takes always precedence over other `IBrowserPublisher` adapters.

I can think of the following (unverified!) approaches to handle this problem:
1. Remove all interfaces from the request except for our service interface.
2. Provide an interface on the context and remove it after processing. However this would probably cause a write operation for every REST request.
3. Do not use `IBrowserPublisher` adapters for REST services, instead use another way to hack into traversal.

I will examine the proposed approaches next to see what could be a suitable solution. Any other ideas or suggestions are welcome.

/cc @tisto @bloodbare @lukasgraf

**Comment by lukasgraf** [comment]
Could we potentially address this by registering a temporary site manager so we can control the component lookup during traversal?

Something along the lines of registering a new local site manager at the start of an API request, re-registering our service adapters with it, and then remove it again at after traversal, but before publishing continues. (Possibly using a similar approach to what `plone.testing` does [when stacking component registries](https://github.com/plone/plone.testing/blob/a5e4fe4d2ec5ca2c7a67efece67e15a627124618/src/plone/testing/zca.py#L55-L113))

Regarding the approaches you mentioned, 1) (removing interfaces from the request) sounds like the least likely to cause unwanted side effects to me.
