### ISSUE TITLE
Unauthorized not handled properly

### ISSUE THREAD

**Issue by zopyx** [plone/plone.rest#30]
Improper credentials should result in 403 response and not 200 response.

response.text in case of the 200 responses contains the HTML code of the Plone login page

```
Pdb++) requests.post(url + '/xmldirector-test', files=files, auth=HTTPBasicAuth(user, password))
<Response [204]>

(Pdb++) requests.post(url + '/xmldirector-test', files=files, auth=HTTPBasicAuth(user, password+'xxxxx'))
<Response [200]>

(Pdb++) requests.post(url + '/xmldirector-test', files=files, auth=HTTPBasicAuth(user, password+'yyyyy'))
<Response [200]>
```

**Comment by tisto** [comment]
I think this has been fixed in the latest 1.0a5 release. Please check and report back.

**Comment by tisto** [comment]
@zopyx I think this issue has been fixed in the latest release. Will close the issue. Feel free to re-open if you disagree...

**Comment by zopyx** [comment]
My test suite passed with 1.0a5, no issues
