### ISSUE TITLE
issue/PR label style?

### ISSUE THREAD

**Issue by jensens** [plone/plone.rest#31]
Shall we apply the label style as for all plone-core here too? 
(same question for plone.restapi, something else?)
if yes I'll add it to the auto-apply script.

**Comment by lukasgraf** [comment]
@jensens I'm all for it :+1:  - is that label style and the exact meaning of those labels documented anywhere though?

I already wanted to read up on those a couple weeks ago, but all I found was https://community.plone.org/t/pull-request-process/675, which seems to be where these labels originated, but lacks a canonical list of their meaning.

**Comment by jensens** [comment]
documentation is at the moment here:
https://docs.google.com/spreadsheets/d/1IQ73bSQ10b0pwoUFn0u8SE4epDdvwjhTiYTDyPAhx7
I need to put this somehow in docs.plone.org ...

**Comment by jensens** [comment]
I did an announcement also here
https://community.plone.org/t/new-labels-for-all-plone-coredev-packages/1044

**Comment by lukasgraf** [comment]
Thank you, that was exactly what I was looking for.
