### ISSUE TITLE
Check for Accept: application/json

### ISSUE THREAD

**Issue by zopyx** [plone/plone.rest#32]
event.py contains a hard-coded check for Accept: application/json.

The Accept: header may contain multiple entries, entries may contain wildcards.

http://www.w3.org/Protocols/HTTP/HTRQ_Headers.html

**Comment by buchi** [comment]
My idea is to make it possible to configure the Accept header per service in ZCML. Something like this:
```
 <plone:service
    method="GET"
    accept="application/json"
    for="plone.dexterity.interfaces.IDexterityContent"
    factory=".demo.Get"
    />
```

Also support for multiple entries can be achieved using the HTTP Accept header syntax, however without parameters (e.g. q=0.8):

```
 <plone:service
    method="GET"
    accept="application/json, application/json-ld"
    for="plone.dexterity.interfaces.IDexterityContent"
    factory=".demo.Get"
    />
```

**Comment by zopyx** [comment]
Support for wildcards would be needed. 

https://pypi.python.org/pypi/python-mimeparse

might help here

**Comment by lukasgraf** [comment]
:+1: for the proposed ZCML - naming the attribute `accept` also makes it clear that this only affects to what service a particular request is **dispatched**.

Dealing with the content-type of the request body and ensuring that only responses with a content-type listed in the `Accept` header are sent then is the responsibility of the particular service implementation.

**Comment by tisto** [comment]
+1
