### ISSUE TITLE
Permission handling?

### ISSUE THREAD

**Issue by zopyx** [plone/plone.rest#36]
What is the vision for dealing with different permissions on API methods?
Should API method perform permission check themselves (as it is implemented in collective.jsonapi.core) or would it make sense to define permissions on the ZCML level in the same way as you define permissions on browser views? In this case the dispatcher would be in charge for checking the permissions against the current security context.

**Comment by buchi** [comment]
My vision ist to have a permission defined in ZCML the same way as it's done with browser views. That's something I have on my todo list and I will probably work on that in the next days.
Of course services can still do additional permission checks.

**Comment by tisto** [comment]
+1 for permissions in zcml.

**Comment by bloodbare** [comment]
+1

El dj., 17 des. 2015 a les 15:54, Timo Stollenwerk (<
notifications@github.com>) va escriure:
