### ISSUE TITLE
difference btw plone.rest and plone.restapi

### ISSUE THREAD

**Issue by thet** [plone/plone.rest#4]
what's the difference between plone.rest and plone.restapi?

**Comment by tisto** [comment]
plone.rest is supposed to be the infrastructure plone.restapi builds upon. It allows developers to provide RESTful endpoints. plone.restapi is a product that will provide a full RESTful API for Plone, e.g. 

I'm still not 100% convinced this separation makes sense. Though, this is also the approach we took in plone.(app.).registry and for other packages as well so far. This is still open for discussion.

**Comment by thet** [comment]
Thanks for explanation. I was wondering, because plone.restapi doesn't depend on plone.rest.

If plone.restapi can build generically upon endpoints, which developer plug into plone.rest via the ZCA, I think this separation can make perfect sense. If plone.restapi is only a thin layer and the only consumer of plone.rest, it might be just more practical to merge those packages.

However, time will show!

**Comment by tisto** [comment]
We are still discussing this separation I hope we can resolve this during the upcoming sprint.
