### ISSUE TITLE
Using '@@' prefix for named services

### ISSUE THREAD

**Issue by cspaeth** [plone/plone.rest#41]
I'm using plone.rest in a small project to build a very basic rest api to read and edit content objects. 
Since buildout fetched the latest release (1.0a4), my named services stopped working. As it turned out, i added '@@' in front of the name when constructing the url (e.g. '/some/folder/@@list' to list the content).

The reason i did this was to distinguish between a service and a possible content item with the name 'list' within this folder. With the new Version and the prefix removed this case is possible again, the traversing will end up at the (nameless) get service of '/some/folder/list' instead of the intended list service of '/some/folder'.

I'm not sure if this functionality was removed intentionally or if i was just using something that wasn't supposed to be used at all, but is there a chance to get the @@ prefix back working again? It seems to be the obvious way to solve that issue to me, but I'm open to different solutions...

Cheers,
   Chriss

**Comment by lukasgraf** [comment]
@cspaeth this might possibly be somewhat related to #42, which we'll take a look at soon.

**Comment by cspaeth** [comment]
Something i added to my code to make my views working again. I don't know if this is a good idea at all, but it works for development:

```
from plone.rest.traverse import RESTWrapper
from zope.component import queryMultiAdapter
from zope.interface import implements
from zope.component import adapts
from zope.publisher.interfaces.browser import IBrowserRequest
from zope.traversing.interfaces import ITraversable

class NamedServiceTraverser(object):
    implements(ITraversable)
    adapts(RESTWrapper, IBrowserRequest)

    def __init__(self, context, request=None):
        self.context = context
        self.request = request

    def traverse(self, name, ignore):
        return queryMultiAdapter((self.context.context, self.request),
                                 name=self.request._rest_service_id + name)

```

```
   <adapter factory=".restfix.NamedServiceTraverser"
        name="view"
        />
```

**Comment by buchi** [comment]
The `@@` prefix for named services was never supposed to work. It worked because of internal implementation details that have changed now.

REST services are technically still browser views, but the name has changed. The name now follows the pattern `{METHOD}_{TYPE}_{SUBTYPE}_{SERVICENAME}`. In your case this would mean that the service should be callable using `/some/folder/GET_application_json_list`or `/some/folder/@@GET_application_json_list`.

Please keep in mind, that this is an implementation detail and could change in future versions.

**Comment by do3cc** [comment]
It would be nice to still have something like @@
there were added to browser views as a way to avoid name clashes with content.

**Comment by cspaeth** [comment]
@buchi As you said, by using the name pattern i would still rely on implementation details. 
Is there a purposed way of dealing with this in a clean way? Feels sort of fundamental to me...

**Comment by buchi** [comment]
Right now there isn't. I could imagine a traversal namespace for services, e.g. `++service++<servicename>`.

**Comment by tisto** [comment]
We decided to use a single @ symbol as a prefix for global resources (to avoid collisions with Plone content). It is highly unlikely to we are going to amend plone.rest in a way to make @@ work. Will close the issue.
