### ISSUE TITLE
Next alpha release.

### ISSUE THREAD

**Issue by tisto** [plone/plone.rest#56]
@buchi @sneridagh @lukasgraf Any blocker for another alpha release? As discussed I would like to make another last alpha release now and then do a beta in two or three weeks if we do not detect any severe bugs.

**Comment by lukasgraf** [comment]
@tisto none that I'd know of - after removing JSON rendering from `plone.rest` with #52 (and adding it again to `plone.restapi` with plone/plone.restapi#103), and the fix from #53 that unbreaks drag&drop file uploads in Plone 5, we're set for another release in my opinion! 🎉 

- [ ] After a new release of `plone.rest` has been made we should add a version constraint to `plone.restapi` that requires that release or newer, and [remove `plone.rest` from `auto-checkout`](https://github.com/plone/plone.restapi/blob/67f22e20197bee12ff4b945fdd6ddebaaf4db6fb/base.cfg#L16)

**Comment by buchi** [comment]
👍 for next alpha release.
I will then deploy it to our production sites. Please wait with the beta until you get some feedback from me.

**Comment by erral** [comment]
I can provide feedback also with the new alpha release, we have it in
production in Plone 4.3.9 to publish content from one site in another.


--
Mikel Larreategi
CodeSyntax

+34 943821780

**Comment by tisto** [comment]
@buchi @lukasgraf @erral: 1.0a6 released: https://pypi.python.org/pypi/plone.rest/1.0a6

**Comment by lukasgraf** [comment]
@tisto woo! 🎉  

@erral please note that you will need to use `plone.restapi` from at least [`99d47494`](https://github.com/plone/plone.restapi/commit/99d47494be81f9b116c7502c8c15b4a106497c69) or newer in order for it to work with this release of `plone.rest`.

**Comment by erral** [comment]
I checked the new plone.rest with the latest plone.restapi in a Plone 4.3.9 where we are using it to publish external content, and it works perfectly.

Nice work! :clap:
