### ISSUE TITLE
OPTIONS returns a body

### ISSUE THREAD

**Issue by ebrehault** [plone/plone.rest#63]
I have just discovered the OPTIONS requests return a body when the Access-Control-Request-Method header mentions GET.

Here is an example with the plone.io server we have set up at Sorrento (that's an up-to-date Plone 5 server with plone.restapi 1.0.a13, but I have the same with 1.0.a14 on local):

```
curl 'http://plone.io/features' -X OPTIONS \
-H 'Access-Control-Request-Method: GET' \
-H 'Origin: http://evil.com/' \
-H 'Accept: */*' \
-H 'Referer: http://localhost:4200/definitions' \
-H 'Access-Control-Request-Headers: authorization,content-type'
```
You will receive the full JSON answer just like if it was a GET.

And if we remove the Access-Control-Request-Method header:
```
curl 'http://plone.io/features' -X OPTIONS \
-H 'Origin: http://evil.com/' \
-H 'Accept: */*' \
-H 'Referer: http://localhost:4200/definitions' \
-H 'Access-Control-Request-Headers: authorization,content-type'
```
Then the body is empty.

So apparently, by setting Access-Control-Request-Method: GET, we turn the OPTIONS into a GET.

@tisto, @buchi any idea what is going on?

**Comment by ebrehault** [comment]
Ok I got it, that's because we only process preflight if we have a CORS policy:
https://github.com/plone/plone.rest/blob/master/src/plone/rest/service.py#L13

If we don't have a policy, we just render the request.
I think it is confusing.
It should either process the preflight (and use a default policy), or throw an error, but not render.

**Comment by buchi** [comment]
@ebrehault yes, this is a bug. #64 should fix that.
