### ISSUE TITLE
Extract the dependency to Products.CMFPlone

### ISSUE THREAD

**Issue by jordic** [plone/plone.rest#81]
I'm evaluating to use this package outside of the plone scope. 
Just on an old zope site that we are trying to modernize, 
but I found the Products.CMFPlone dependency, 
that blocks us for using it 
(it could be amazing, to have that declarative layer for rest services)
https://github.com/plone/plone.rest/blob/master/src/plone/rest/traverse.py

There are also the testing machinery, that is tied to the plone.testing.
Any ideas or workaround for this. (I can't install plone) 
An ugly solution is to just provide a (custom "fake" Products.CMFPlone), to let
pip install this package, but perhaps yours can help me on something better.
(not so ugly...)

**Comment by tisto** [comment]
@jordic I'd love to see this package working without the CMFPlone dependency. Though, we did not put any effort into this so far. plone.testing should not have a Plone dependency.

**Comment by tisto** [comment]
@jordic if I am not mistaken this is the only (undeclared) dependency on CMFPlone:

https://github.com/plone/plone.rest/blob/9c6f6dbd8794de8ab1dd4c85aa425d416b184d69/src/plone/rest/traverse.py#L2

setup.py just declares a CMFCore dependency.

**Comment by davisagli** [comment]
That one looks easy to fix -- just use Products.CMFCore.interfaces.ISiteRoot instead.

**Comment by jordic** [comment]
yeah! @tisto! we have cmfcore :) I looked ar it and confused names.
sounds good if I do a PR with conditional import from plone or from cmfcore, the ISiteRoot Interface?

**Comment by sunew** [comment]
@jordic I think just using CMFCore would be fine?

**Comment by davisagli** [comment]
Products.CMFPlone.interfaces.siteroot.IPloneSiteRoot extends Products.CMFCore.interfaces.ISiteRoot, so it should be fine to just use ISiteRoot.

**Comment by tisto** [comment]
@jordic I'd go with @davisagli's recommendation and use ISiteRoot from CMFCore. If you do a pull request I can do a release right away.

**Comment by tisto** [comment]
@jordic do you still plan to work on this? The PR should be trivial and I am happy to review, merge and do a release.

**Comment by jordic** [comment]
So sorry! I had been out for so many time! Will try to do it on the future, but right now, we can't use it (our super, super old zope deployment, has so many other issues to deal with). Frist, we need to decouple a big part (we are on the process), then update the remaining part to zope4 (and after this, we will be able to use this package, and start creating services aroun it). Anywyay, if anyone else, picks the issue, I will do it.

**Comment by tisto** [comment]
@jordic here you go: https://github.com/plone/plone.rest/pull/89

**Comment by jordic** [comment]
Ohhh! That's awesome.. anyway thought there are still other deps here:
https://github.com/plone/plone.rest/blob/master/src/plone/rest/errors.py

**Comment by tisto** [comment]
@jordic ok, I guess that's mainly plone.app.redirector, right? That shouldn't be too hard to make optional as well...

**Comment by tisto** [comment]
@jordic fixed and released with https://pypi.org/project/plone.rest/1.6.0#id1. Pls test and report back.
