### ISSUE TITLE
plone.rest should consider all calls to /api to be REST calls

### ISSUE THREAD

**Issue by tisto** [plone/plone.rest#87]
Using content negotiation in REST APIs is considered to be the correct way of doing things in sync with the HTTP specification. Though, in real life, there are some downsides to this approach:

- Debugging and dev approachability: The dev always has to copy a CURL command to reproduce a REST call. Dev tools make things a lot easier but there is still a barrier and it confuses unexperienced devs

- Cache poisoning: Turns our cache servers do not consider the content-type HTTP header and treat JSON and HTML documents as the same

The idea would be that we add an additional traversal hook that considers all calls that start with "/api" as plone.rest calls. The existing content-negotiation should stay in place for backwards compatibility and option if people want to use it.

**Comment by raphael-ritz** [comment]
+1
This would also ease the support of use cases where one needs to authenticate through a 3rd party IdP and where the auth methods differ for human (Shibboleth) versus machine (OpenIdConnect) access.

**Comment by jensens** [comment]
for cache poisoning see also #73

**Comment by hvelarde** [comment]
documentation needs to be written on how to avoid the cache poisoning issue mentioned before as it will be still present if the existing content-negotiation stays in place.

**Comment by jensens** [comment]
I added a kind of request for comments/proposal how to solve this for different use case to a branch.
https://github.com/plone/plone.rest/tree/rest-traverser#content-negotiation
diff is 
https://github.com/plone/plone.rest/commit/ea409fdce11588616cea9c090d3eb261bd871820

I think using a classic zope traverser with ist ++ URLs does not conflict with other names, like api does.

**Comment by tisto** [comment]
We have ++api++ now...
