### ISSUE TITLE
Wheel missing

### ISSUE THREAD

**Issue by jensens** [plone/plone.rest#93]
Even if setup.cfg states there should be a wheel released, on PyPI there is no wheel uploaded.

**Comment by mauritsvanrees** [comment]
During the last release, the `setup.cfg` was not there yet. Should be solved automatically with the next release. But let's keep this issue open to check.

**Comment by tisto** [comment]
Wheel for 1.6.0 is present: https://pypi.org/project/plone.rest/#files
