### ISSUE TITLE
New release please

### ISSUE THREAD

**Issue by mauritsvanrees** [plone/plone.rest#94]
Can we have a new release?

**Comment by tisto** [comment]
@mauritsvanrees I made two brown bag releases now. Obviously I am not smart enough to make releases with towncrier...

**Comment by tisto** [comment]
@mauritsvanrees FYI: I tried to make releases via the plone.rest repo and it seems towncrier has not been set up properly in the plone.rest repo. It works via buildout.coredev. Will you be in Ferrara? We should schedule a release team meeting there...

**Comment by mauritsvanrees** [comment]
Sorry to hear that you had troubles again.

I set it up correctly in `plone.restapi` earlier this year:

```
[releaser]
recipe = zc.recipe.egg
eggs =
    zest.releaser[recommended]
    zestreleaser.towncrier
    towncrier
    readme
    docutils
```

(A few of those eggs may not be needed, and I did not add all of them, but they don't hurt.)

I did not copy that to `plone.rest`, because I am not used to having a `bin/release` script in each package. `plone.rest` is missing some of the eggs, which makes it not pick up the news snippets:

```
[releaser]
recipe = zc.recipe.egg
eggs =
    zest.releaser
    httpie
```

Release team meeting would definitely be good.

**Comment by tisto** [comment]
thanks @mauritsvanrees! will give it a shot next time. I know that plone.rest and plone.restapi are somehow "special" packages. I put all my effort into Volto and plone.restapi right now, so I rarely checkout buildout.coredev these days. Looking forward to seeing you in Ferrara!
